# Generated by Django 5.1.5 on 2025-01-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('tenth_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contact_number', models.CharField(max_length=15)),
                ('passing_year', models.IntegerField()),
                ('current_school', models.CharField(max_length=200)),
                ('interested_branch', models.CharField(max_length=100)),
            ],
        ),
    ]
